/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package home;

import controller.dbConnection;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ade Mulyana
 */
public class songCard extends javax.swing.JPanel {

    /**
     * Creates new form songCard
     */
    private dbConnection db;
    String pathImg = "";
    public songCard(int songId, String songTitle,int singerId,String album, String duration, String image) {
        initComponents();
        idLabelHide.setText(Integer.toString(songId));
        titleSongLabel.setText(songTitle);
        idSingerLabel.setText(Integer.toString(singerId));
        albumLabel.setText(album);
        durationLabel.setText(duration);
        pathImg = "src\\image\\"+image;
        ImageIcon ic = new ImageIcon(new ImageIcon(pathImg).getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH));
        imageLabel.setIcon(ic);
    }
    
    public void deleteData() {
        // Remove Data from List
        int id = 0;
        String idTemp = idLabelHide.getText();
        try {
            id = Integer.parseInt(idTemp); // mengonversi nilai string menjadi integer dan menyimpannya ke dalam variabel id
        } catch (NumberFormatException ex) {
            System.out.println("Nilai tidak valid");
        }
        db = new dbConnection();

        String sql = "DELETE FROM title_song WHERE song_id='"+id+"'";
        db.updateQuery(sql);
        
        // Update Table

        // Reset Form
//        resetForm();
        
        // Show Information
        System.out.println("Delete success!");
        JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idLabelHide = new javax.swing.JLabel();
        titleSongLabel = new javax.swing.JLabel();
        idSingerLabel = new javax.swing.JLabel();
        albumLabel = new javax.swing.JLabel();
        durationLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        idLabelHide.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        idLabelHide.setForeground(new java.awt.Color(255, 255, 255));
        idLabelHide.setText("jLabel1");

        titleSongLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleSongLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleSongLabel.setText("jLabel2");

        idSingerLabel.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        idSingerLabel.setForeground(new java.awt.Color(255, 255, 255));
        idSingerLabel.setText("jLabel3");

        albumLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        albumLabel.setForeground(new java.awt.Color(255, 255, 255));
        albumLabel.setText("jLabel4");

        durationLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        durationLabel.setForeground(new java.awt.Color(255, 255, 255));
        durationLabel.setText("jLabel5");

        deleteButton.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        deleteButton.setText("delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        updateButton.setText("update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        imageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idLabelHide)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(titleSongLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(idSingerLabel)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(albumLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(durationLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idLabelHide)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titleSongLabel)
                            .addComponent(albumLabel)
                            .addComponent(durationLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteButton)
                            .addComponent(updateButton)
                            .addComponent(idSingerLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int dialogButton = 0;
        int dialogResult = JOptionPane.showConfirmDialog (null, "Are you sure delete this song from your playlist?","Warning",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION) {
            deleteData();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        String idTemp = idLabelHide.getText();
        int idInt = 0;
        idInt = Integer.parseInt(idTemp);
        updateSongFrame panel = new updateSongFrame(idInt);
        panel.setVisible(true);
    }//GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel albumLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JLabel idLabelHide;
    private javax.swing.JLabel idSingerLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel titleSongLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
